# Generated by Django 2.0.4 on 2018-04-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_user_worker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
        migrations.AddField(
            model_name='service',
            name='service',
            field=models.CharField(choices=[('Appliance Repair', 'Appliance Repair'), ('Door Installation', 'Door Installation'), ('Electrician', 'Electrician'), ('Flooring', 'Flooring'), ('Upholstery', 'Upholstery'), ('Garage', 'Garage'), ('Home Security System', 'Home Security System'), ('Interior Design', 'Interior Design'), ('Landscaping', 'Landscaping'), ('Lighting Installation', 'Lighting Installation'), ('Moving', 'Moving'), ('Pest Control', 'Pest Control'), ('Plumber', 'Plumber'), ('Roofing', 'Roofing'), ('Auto', 'Auto'), ('Auto Body Repair', 'Auto Body Repair'), ('Auto Repair', 'Auto Repair'), ('Auto Service', 'Auto Service'), ('Health', 'Health'), ('Chiropractor', 'Chiropractor'), ('Counseling & Mental Health', 'Counseling & Mental Health'), ('Dentistry', 'Dentistry'), ('Dermatology', 'Dermatology'), ('Eye Care', 'Eye Care'), ('Fitness & Weight Management', 'Fitness & Weight Management'), ('Health Care Facility', 'Health Care Facility'), ('Home Health Care', 'Home Health Care'), ('Medical Specialist', 'Medical Specialist'), ('Pets', 'Pets'), ('Pet Care & Health Services', 'Pet Care & Health Services'), ('Finance Advising', 'Finance Advising'), ('Transportation', 'Transportation'), ('Wedding Planning', 'Wedding Planning')], default='Appliance Repair', max_length=100),
        ),
    ]
