# Generated by Django 2.0.4 on 2018-04-24 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_auto_20180424_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='service',
            name='rating',
        ),
    ]
