# Generated by Django 2.0.4 on 2018-04-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_auto_20180424_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='id',
        ),
        migrations.AddField(
            model_name='worker',
            name='workerID',
            field=models.AutoField(default=-1, primary_key=True, serialize=False),
        ),
    ]
