# Generated by Django 2.0.4 on 2018-04-29 01:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_auto_20180424_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('message', models.TextField(max_length=500)),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='projectapp.Service')),
            ],
            options={
                'ordering': ('rating',),
            },
        ),
    ]
