# Generated by Django 2.0.4 on 2018-04-27 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('rating',)},
        ),
    ]
