# Generated by Django 2.0.4 on 2018-04-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_auto_20180425_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='workerID',
            field=models.AutoField(default='-1', primary_key=True, serialize=False),
        ),
    ]
