# Generated by Django 2.0.4 on 2018-04-25 23:52

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0007_auto_20180425_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='workerID',
        ),
        migrations.AddField(
            model_name='worker',
            name='id',
            field=models.AutoField(auto_created=True, default=builtins.id, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
